### ISSUE TITLE
Bot has duplicated message while streaming.

### ISSUE THREAD

**Issue by w013nad** [streamlit/snowflake-arctic-st-demo#15]
While it is generating the next response, it duplicates the previous one during the streaming process. Not sure what is causing it.

![image](https://github.com/streamlit/snowflake-arctic-st-demo/assets/26445256/d0650ff2-f781-4976-8388-ee3c1ba74cec)

**Comment by sfc-gh-cfrasca** [comment]
Thank you for flagging this! This issue should be [resolved](https://github.com/streamlit/snowflake-arctic-st-demo/pull/16) now.
